# This is a basic workflow to help you get started with Actions

name: Deploy to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Login to GHCR
      uses: mr-smithers-excellent/docker-build-push@v5
      id: login-ghcr
      with:
        image: github-repo/image-name
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        GHCR_REGISTRY: ${{ steps.login-ghcr.outputs.registry }}
        GHCR_REPOSITORY: docker_nodejs_demo
        IMAGE_TAG: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      run: |
        docker build -t $GHCR_REGISTRY/$GHCR_REPOSITORY:$IMAGE_TAG .
        docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:$IMAGE_TAG
