# This is a basic workflow to help you get started with Actions

name: Deploy to ECR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

jobs:
  
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Get tag
      id: repository
      run: echo  "::set-output name=tag::$(git describe --tags HEAD)"
    
    - name: Login to GHCR
      uses: mr-smithers-excellent/docker-build-push@v5
      id: login-ghcr
      with:
        image: nodejs/demo
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: tag push 
      uses: shrink/actions-docker-registry-tag@v3
      with:
        registry: ghcr.io
        repository: ${{ github.repository }}
        target: sha-${{ github.sha }}
        tags: |
          ${{ steps.repository.outputs.tag }}
          latest

#     - name: Build, tag, and push image to Amazon ECR
#       env:
#         GHCR_REGISTRY: ghcr.io/shboddu
#         GHCR_REPOSITORY: docker_nodejs_demo
        
#       run: |
#         IMAGE_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
#         docker build -t $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.tag }} .
#         docker push $GHCR_REGISTRY/$GHCR_REPOSITORY:${{ env.tag }}
