---
name: Build and publish the image from reusable repo

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'


jobs:
  build-and-test:
    permissions:
      id-token: write # need this for OIDC
      contents: read
    uses: https://github.com/shboddu/poetry-test/blob/master/.github/GitHub-ci2.yaml@master
    with:
      env: ${{ github.event.inputs.environment }}
    secrets: inherit
